name: bigbro
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  teledart: ^0.5.6
  dio: ^5.1.1
  hive: ^2.2.3
  uuid: ^3.0.7
  logger: ^1.3.0
  tinkoff_acquiring: ^3.0.10
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
